name: mappee
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ./domain
  
  data:
    path: ./data

  cupertino_icons: ^1.0.2
  # State managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Network
  dio: ^5.4.0
  # Code generator
  freezed_annotation: ^2.4.1
  # DI
  get_it: ^7.6.4
  # Routing
  auto_route: ^7.8.0
  flutter_secure_storage: ^9.0.0
  stacked: ^3.4.1+1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # code generator
  build_runner: ^2.4.7
  freezed: ^2.4.5
  auto_route_generator: ^7.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
  
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-VariableFont_wght.ttf