name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.1
  # path: ^1.8.0
  dartz: ^0.10.1


dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  lints: ^2.0.0
  test: ^1.21.0
